const columns = [
  {
    name: "No.",
    selector: "no",
    center: true,
    sortable: true,
    compact: true,
    width: "50px",
  },
  {
    name: "Kode Cabang",
    selector: "kodeCabang",
    center: true,
    sortable: true,
    compact: true,
    width: "250px",
  },
  {
    name: "No PO",
    selector: "noPo",
    center: true,
    sortable: true,
    compact: true,
    width: "150px",
  },
  {
    name: "No Aplikasi",
    selector: "noApp",
    center: true,
    sortable: true,
    compact: true,
    width: "150px",
  },
  {
    name: "Kustomer",
    selector: "kustomer",
    center: true,
    sortable: true,
    compact: true,
    width: "250px",
  },
  {
    name: "Penumpang",
    selector: "penumpang",
    center: true,
    sortable: true,
    compact: true,
    width: "250px",
  },
  {
    name: "No Rek",
    selector: "noRek",
    center: true,
    sortable: true,
    compact: true,
    width: "100px",
  },
  {
    name: "Bank",
    selector: "bank",
    center: true,
    sortable: true,
    compact: true,
    width: "250px",
  },
  {
    name: "Pencairan",
    selector: "pencairan",
    center: true,
    sortable: true,
    compact: true,
    width: "150px",
  },
  {
    name: "Cabang",
    selector: "cabang",
    center: true,
    sortable: true,
    compact: true,
    width: "150px",
  },
];

export default columns;
